### ISSUE TITLE
bot私聊信息有反应，但是群消息接收后无应答

### ISSUE THREAD

**Issue by as6296463** [LYshiying/ui_bot#2]
依据步骤下来部署后，除了没有./res/source/blhxwiki/下找到chromedriver外，在网上下了个能使用的chromedriver启动，bot能接收到私聊的消息，但是像发图片的消息没有应答，不知道是不是pixiv的value填错了（按步骤的要求找到code复制的），同时群消息接收到后不会进行处理没有反应
![001](https://user-images.githubusercontent.com/37761817/140636173-4348217c-a099-43f5-8160-87f1ef9547dc.png)
![002](https://user-images.githubusercontent.com/37761817/140636174-fe77321c-74ca-4af1-878a-c04d35d93990.png)
![003](https://user-images.githubusercontent.com/37761817/140636175-06cd60d9-b029-4315-b5a6-0c13dc0b9501.png)
![004](https://user-images.githubusercontent.com/37761817/140636176-8f34f0a7-534e-4a9b-9918-a159d5afa65b.png)
![005](https://user-images.githubusercontent.com/37761817/140636177-a9725928-a76e-4c7e-8401-6199b06230b9.png)
![006](https://user-images.githubusercontent.com/37761817/140636179-b0258704-b62b-4cfb-8ca2-9fde471fda88.png)
![007](https://user-images.githubusercontent.com/37761817/140636180-8f59bd3d-d0fa-4a30-a5a3-6a633ca8a9a1.png)
![008](https://user-images.githubusercontent.com/37761817/140636182-7b3694d2-0e13-4c09-bc63-d97438456705.png)
![009](https://user-images.githubusercontent.com/37761817/140636183-65e885ca-d889-4007-9520-d38464ba14b3.png)
![010](https://user-images.githubusercontent.com/37761817/140636184-b6b94cdb-fada-42f2-8daf-d919eb817d4c.png)
。

**Comment by shirumesu** [comment]
非常不好意思，因为我上github频率不高，qq邮箱也被各种信息轰炸基本没怎么看，现在才留意到这条issue，如果你还需要我的帮助的话:

看到你配置了`NICKNAME`一项，这一项的意思是触发机器人从:
`@xxx 色图`可以变为`xxx 色图`, 不再需要@了
所以为了匹配所有指令实际上推荐配置为空`""`, 因为没有聊天机器人的接入, 本身配置为空也不会有什么影响

然后你私聊setu成功发送了, 是因为私聊不需要检查`是否正在对机器人说话`这一项, 群里按照你的配置应该是发送`qqq help`

另外色图消息为空……暂时不能确定是什么原因

实在抱歉晚了那么多回复这条issue 如果你已经使用上别的bot了的话那么祝你好运，如果依旧打算使用uibot那希望以后可以继续交流 谢谢你的issue！

**Comment by as6296463** [comment]
> 非常不好意思，因为我上github频率不高，qq邮箱也被各种信息轰炸基本没怎么看，现在才留意到这条issue，如果你还需要我的帮助的话:
> 
> 看到你配置了`NICKNAME`一项，这一项的意思是触发机器人从: `@xxx 色图`可以变为`xxx 色图`, 不再需要@了 所以为了匹配所有指令实际上推荐配置为空`""`, 因为没有聊天机器人的接入, 本身配置为空也不会有什么影响
> 
> 然后你私聊setu成功发送了, 是因为私聊不需要检查`是否正在对机器人说话`这一项, 群里按照你的配置应该是发送`qqq help`
> 
> 另外色图消息为空……暂时不能确定是什么原因
> 
> 实在抱歉晚了那么多回复这条issue 如果你已经使用上别的bot了的话那么祝你好运，如果依旧打算使用uibot那希望以后可以继续交流 谢谢你的issue！

没事，谢谢你的回复，后面有时间我会重新去尝试下部署，感谢你的帮助，确实没有看到昵称那块的问题。
