### ISSUE TITLE
BOT.py运行闪退

### ISSUE THREAD

**Issue by littlezimo** [LYshiying/ui_bot#3]
1. ./res/source下没有/blhxwiki文件夹，blhxwiki只在plugin里找到，能用edgedrive吗？
2. go-cqhttp最初始配置是选3反向吗？
3. 双击bot.py启动后闪退
第四步以上都能顺利完成，求助！

**Comment by shirumesu** [comment]
非常不好意思，因为我上github频率不高，qq邮箱也被各种信息轰炸基本没怎么看，现在才留意到这条issue，如果你还需要我的帮助的话:

1. 现在因为selenium在部分网络环境(例如云服务器)上响应很慢, 所以换为了普通爬虫, 不再需要了
2. 是的 反向 WebSocket, 可以参照Nonebot官方文档的[安装教程](https://docs.nonebot.dev/guide/getting-started.html)
3. 我需要更多日志来判断原因, 如果可以的话请在shell或者windows terminal中打开, 这样就算程序退出了也会留下错误的输出

实在抱歉晚了那么多回复这条issue 如果你已经使用上别的bot了的话那么祝你好运，如果依旧打算使用uibot那希望以后可以继续交流 谢谢你的issue！

**Comment by shi-g-c** [comment]
运行bot.py的时候显示TypeError: 'type' object is not subscriptable。让后就是config.py里面很多api不知道该怎么填，可能是我太菜了吧，呜呜呜。

**Comment by shirumesu** [comment]
> 运行bot.py的时候显示TypeError: 'type' object is not subscriptable。让后就是config.py里面很多api不知道该怎么填，可能是我太菜了吧，呜呜呜。

你好！
不知道能不能回复得到……
`TypeError: 'type' object is not subscriptable.` 这里是因为python版本不够有些新版本的东西无法使用，要升级到python3.9以上
然后config.py里可以跟着[文档](https://uibot.uisbox.com/#/zh-cn/Api/)填写…很多都是填字符串就可以了 abc = "123123"的形式，加上双引号就好
