### ISSUE TITLE
python bot.py提示找不到指定路径

### ISSUE THREAD

**Issue by HikasaHana** [LYshiying/ui_bot#5]
Traceback (most recent call last):
  File "*******\ui_bot\bot.py", line 108, in <module>
    start()
  File "*******\ui_bot\bot.py", line 61, in start
    os.makedirs(config.res, exist_ok=True)
  File "*******\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ''

**Comment by HikasaHana** [comment]
纯py小白，无从下手😭

**Comment by shirumesu** [comment]
看着应该是res路径没填对
如果是win11的话: 进根目录右键res文件夹`Ctrl + Shift + C`复制文件路径 填进去`config.py`的res里
如果是win10的话: 进res文件夹右键source文件夹 → 属性 → 复制`位置`那一行的地址填进去

**Comment by HikasaHana** [comment]
> 看着应该是res路径没填对 如果是win11的话: 进根目录右键res文件夹`Ctrl + Shift + C`复制文件路径 填进去`config.py`的res里 如果是win10的话: 进res文件夹右键source文件夹 → 属性 → 复制`位置`那一行的地址填进去

谢谢谢谢，解决了🙇‍♂️🙇‍♂️🙇‍♂️真的是配置文件填漏了，太低级错误了
